# Файл docker-compose.yml
version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: tortegg/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
  frontend:
    env_file: .env
    image: tortegg/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    # Сбилдить и запустить образ,
    # описанный в Dockerfile в папке gateway
    image: tortegg/taski_gateway
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
